FROM node:20
ARG NEXT_PUBLIC_SERVER_URL
ARG PAYLOAD_SECRET
ARG MONGODB_URL
ARG TRANSACTION_FEE_PRICE_ID
ARG STRIPE_SECRET_KEY
ARG STRIPE_WEBHOOK_SECRET
ARG RESEND_API_KEY

WORKDIR /usr/src/app
COPY . .
RUN npm install
RUN npm run build
CMD ["npm", "start"]